name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Replace with the version you are using

      - name: Build application
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish "path/to/test_api/test_api.csproj" --configuration Release --output "published-app"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "test_api"  # Replace with your Azure app's name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "published-app"
